# Generated by Django 5.1.3 on 2024-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='_zip',
            field=models.IntegerField(default=100000, max_length=6),
            preserve_default=False,
        ),
    ]
